CREATE DATABASE `swtdblocal` /*!40100 DEFAULT CHARACTER SET utf8 */;
CREATE TABLE `asset` (
  `AssetId` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `AssetName` varchar(45) NOT NULL,
  `BalanceFree` decimal(20,8) DEFAULT '-1.00000000',
  `BalanceLocked` decimal(20,8) DEFAULT '-1.00000000',
  `ModifiedDate` datetime DEFAULT NULL,
  PRIMARY KEY (`AssetId`),
  UNIQUE KEY `AssetId_UNIQUE` (`AssetId`),
  UNIQUE KEY `AssetName_UNIQUE` (`AssetName`)
) ENGINE=InnoDB AUTO_INCREMENT=59735 DEFAULT CHARSET=utf8;

CREATE TABLE `botlog` (
  `BotLogId` int(11) NOT NULL AUTO_INCREMENT,
  `Symbol` varchar(45) DEFAULT NULL,
  `ShortLog` longtext,
  `LongLog` longtext,
  `CreatedDate` datetime DEFAULT NULL,
  PRIMARY KEY (`BotLogId`),
  UNIQUE KEY `BotLogId_UNIQUE` (`BotLogId`)
) ENGINE=InnoDB AUTO_INCREMENT=12378 DEFAULT CHARSET=utf8;

CREATE TABLE `botparameters` (
  `BotParametersId` int(11) NOT NULL AUTO_INCREMENT,
  `ApiKey` varchar(1000) DEFAULT NULL,
  `SecretKey` varchar(1000) DEFAULT NULL,
  `MaxConcurrentTradeNumber` int(11) DEFAULT '0',
  `MinPrice` decimal(20,8) DEFAULT '0.00000000',
  `MinDailyVolume` decimal(20,8) DEFAULT '0.00000000',
  `RunOnSelectedMarkets` bit(1) DEFAULT b'1',
  `MarketUpdateDate` int(11) DEFAULT '0',
  PRIMARY KEY (`BotParametersId`),
  UNIQUE KEY `BotParametersId_UNIQUE` (`BotParametersId`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8;

CREATE TABLE `indicatorlog` (
  `IndicatorLogId` int(11) NOT NULL AUTO_INCREMENT,
  `Symbol` varchar(45) DEFAULT NULL,
  `CreatedDate` datetime DEFAULT NULL,
  `CandleDate` datetime DEFAULT NULL,
  `CurrentPrice` decimal(20,8) DEFAULT '0.00000000',
  `R_ROC_Value` decimal(10,2) DEFAULT '0.00',
  `R_ROC_Signal` bit(1) DEFAULT b'0',
  `R_MPT_Value` decimal(20,8) DEFAULT '0.00000000',
  `R_NV_BuyPercent` decimal(20,2) DEFAULT '0.00',
  `R_NV_SellPercent` decimal(20,2) DEFAULT '0.00',
  `R_NV_NetVolume` decimal(20,8) DEFAULT '0.00000000',
  `R_ROC_MPT_Signal` bit(1) DEFAULT b'0',
  `Trend_Signal` bit(1) DEFAULT b'0',
  `R_NV_Signal` bit(1) DEFAULT b'0',
  `R_Signal` bit(1) DEFAULT b'0',
  `F_ROC_Value` decimal(10,2) DEFAULT '0.00',
  `F_ROC_Signal` bit(1) DEFAULT b'0',
  `F_ROC_MPT_Signal` bit(1) DEFAULT b'0',
  `F_NV_Signal` bit(1) DEFAULT b'0',
  `F_Signal` bit(1) DEFAULT b'0',
  `S_ROC_Value` decimal(10,2) DEFAULT '0.00',
  `S_Rsi_Value` decimal(10,2) DEFAULT '0.00',
  `S_Stoch_Value` decimal(10,2) DEFAULT '0.00',
  `S_ROC_Signal` bit(1) DEFAULT b'0',
  `S_Rsi_Signal` bit(1) DEFAULT b'0',
  `S_Stoch_Signal` bit(1) DEFAULT b'0',
  `S_Signal` bit(1) DEFAULT b'0',
  `R_Open_Count` int(11) DEFAULT '0',
  `F_Open_Count` int(11) DEFAULT '0',
  `S_Open_Count` int(11) DEFAULT '0',
  PRIMARY KEY (`IndicatorLogId`),
  UNIQUE KEY `IndicatorLogId_UNIQUE` (`IndicatorLogId`)
) ENGINE=InnoDB AUTO_INCREMENT=54555 DEFAULT CHARSET=utf8;

CREATE TABLE `market` (
  `MarketId` int(11) NOT NULL AUTO_INCREMENT,
  `Symbol` varchar(45) NOT NULL DEFAULT '',
  `BaseAsset` varchar(45) DEFAULT NULL,
  `QuoteAsset` varchar(45) DEFAULT NULL,
  `AmountDecimalDigits` int(11) DEFAULT '0',
  `MinQuantity` decimal(20,8) DEFAULT '0.00000000',
  `MinAmountToTrade` decimal(20,8) DEFAULT '0.00000000',
  `IsSelected` bit(1) NOT NULL DEFAULT b'0',
  `LastPrice` decimal(20,8) DEFAULT '0.00000000',
  `R_ROC_Value` decimal(10,2) DEFAULT '0.00',
  `R_ROC_Signal` bit(1) DEFAULT b'0',
  `R_MPT_Value` decimal(20,8) DEFAULT '0.00000000',
  `R_NV_BuyPercent` decimal(20,2) DEFAULT '0.00',
  `R_NV_SellPercent` decimal(20,2) DEFAULT '0.00',
  `R_NV_NetVolume` decimal(20,2) DEFAULT '0.00',
  `R_ROC_MPT_Signal` bit(1) DEFAULT b'0',
  `Trend_Signal` bit(1) DEFAULT b'0',
  `R_NV_Signal` bit(1) DEFAULT b'0',
  `F_NV_Signal` bit(1) DEFAULT b'0',
  `R_Signal` bit(1) DEFAULT b'0',
  `F_ROC_Value` decimal(10,2) DEFAULT '0.00',
  `F_ROC_Signal` bit(1) DEFAULT b'0',
  `F_ROC_MPT_Signal` bit(1) DEFAULT b'0',
  `F_Signal` bit(1) DEFAULT b'0',
  `S_ROC_Value` decimal(10,2) DEFAULT '0.00',
  `S_Rsi_Value` decimal(10,2) DEFAULT '0.00',
  `S_Stoch_Value` decimal(10,2) DEFAULT '0.00',
  `S_ROC_Signal` bit(1) DEFAULT b'0',
  `S_Rsi_Signal` bit(1) DEFAULT b'0',
  `S_Stoch_Signal` bit(1) DEFAULT b'0',
  `S_Signal` bit(1) DEFAULT b'0',
  `ModifiedDate` datetime DEFAULT NULL,
  `CheckedDate` datetime DEFAULT NULL,
  `IsTradable` bit(1) NOT NULL DEFAULT b'0',
  `DailyPrice` decimal(20,8) DEFAULT '0.00000000',
  `DailyVolume` decimal(20,2) DEFAULT '0.00',
  PRIMARY KEY (`MarketId`),
  UNIQUE KEY `Symbol` (`Symbol`)
) ENGINE=InnoDB AUTO_INCREMENT=34564 DEFAULT CHARSET=utf8;

CREATE TABLE `qcparameters` (
  `QcParametersId` int(11) NOT NULL AUTO_INCREMENT,
  `Asset` varchar(55) DEFAULT NULL,
  `MinVolume1` decimal(10,0) NOT NULL DEFAULT '0',
  `MaxVolume1` decimal(10,0) NOT NULL DEFAULT '0',
  `Perc1` decimal(10,2) NOT NULL DEFAULT '0.00',
  `MinVolume2` decimal(10,0) NOT NULL DEFAULT '0',
  `MaxVolume2` decimal(10,0) NOT NULL DEFAULT '0',
  `Perc2` decimal(10,2) NOT NULL DEFAULT '0.00',
  `MinVolume3` decimal(10,0) NOT NULL DEFAULT '0',
  `MaxVolume3` decimal(10,0) NOT NULL DEFAULT '0',
  `Perc3` decimal(10,2) NOT NULL DEFAULT '0.00',
  `MinVolume4` decimal(10,0) NOT NULL DEFAULT '0',
  `MaxVolume4` decimal(10,0) NOT NULL DEFAULT '0',
  `Perc4` decimal(10,2) NOT NULL DEFAULT '0.00',
  `MinVolume5` decimal(10,0) NOT NULL DEFAULT '0',
  `MaxVolume5` decimal(10,0) NOT NULL DEFAULT '0',
  `Perc5` decimal(10,2) NOT NULL DEFAULT '0.00',
  `MinVolume6` decimal(10,0) NOT NULL DEFAULT '0',
  `MaxVolume6` decimal(10,0) NOT NULL DEFAULT '0',
  `Perc6` decimal(10,2) NOT NULL DEFAULT '0.00',
  `DailySpendPerc` decimal(10,2) DEFAULT '0.00',
  `TradeEnabled` bit(1) NOT NULL DEFAULT b'0',
  `RebuyTriggerAmount` decimal(20,8) DEFAULT '0.00000000',
  `RebuyAmount` decimal(20,8) DEFAULT '0.00000000',
  PRIMARY KEY (`QcParametersId`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8;

CREATE TABLE `strategyparameters` (
  `StrategyParametersId` int(11) NOT NULL AUTO_INCREMENT,
  `Timeframe` varchar(45) DEFAULT '15m',
  `ROC_IndicatorEnabled` bit(1) DEFAULT b'0',
  `ROC_AppliedPrice_R` varchar(45) DEFAULT '0',
  `ROC_AppliedPrice_F` varchar(45) DEFAULT '0',
  `ROC_Period_R` int(11) DEFAULT '0',
  `ROC_Period_F` int(11) DEFAULT '0',
  `ROC_R_BuyIncreasePercentage` decimal(10,2) DEFAULT '0.00',
  `ROC_F_BuyDecreasePercentage` decimal(10,2) DEFAULT '0.00',
  `MPT_IndicatorEnabled` bit(1) DEFAULT b'0',
  `MPT_AppliedPrice` varchar(45) DEFAULT 'close',
  `MPT_ShortMAPeriod` int(11) DEFAULT '0',
  `MPT_LongMAPeriod` int(11) DEFAULT '0',
  `NV_IndicatorEnabled` bit(1) DEFAULT b'0',
  `NV_IncreasePercentage` decimal(10,2) DEFAULT '0.00',
  `NV_MinNetVolume` decimal(10,2) DEFAULT '0.00',
  `TREND_IndicatorEnabled` bit(1) DEFAULT b'0',
  `TREND_AppliedPrice` varchar(45) DEFAULT 'close',
  `TREND_LongEmaPeriod` int(11) DEFAULT '0',
  `TREND_ShortEmaPeriod` int(11) DEFAULT '0',
  `SELL_IndicatorEnabled` bit(1) DEFAULT b'0',
  `SELL_DecreasePercentage` decimal(10,2) DEFAULT '0.00',
  `SELL_Period` int(11) DEFAULT '0',
  `SELL_RSI_AppliedPrice` varchar(45) DEFAULT 'close',
  `SELL_RSI_Period` int(11) DEFAULT '0',
  `SELL_RSI_UpperLevel` decimal(10,2) DEFAULT '0.00',
  `SELL_RSI_LowerLevel` decimal(10,2) DEFAULT '0.00',
  `SELL_Stoch_AppliedPrice` varchar(45) DEFAULT 'closeclose',
  `SELL_Stoch_KPeriod` int(11) DEFAULT '0',
  `SELL_Stoch_DPeriod` int(11) DEFAULT '0',
  `SELL_Stoch_Slowing` int(11) DEFAULT '0',
  `SELL_Stoch_UpperLevel` decimal(10,2) DEFAULT '0.00',
  `SELL_Stoch_LowerLevel` decimal(10,2) DEFAULT '0.00',
  `R_TradingEnabled` bit(1) DEFAULT b'0',
  `R_SL1Percentage` decimal(10,2) DEFAULT '0.00',
  `R_SL2Percentage` decimal(10,2) DEFAULT '0.00',
  `R_SLTimerInMinutes` int(11) DEFAULT '0',
  `R_TSLActivationPercentage` decimal(10,2) DEFAULT '0.00',
  `R_TSLTrailPercentage` decimal(10,2) DEFAULT '0.00',
  `F_TradingEnabled` bit(1) DEFAULT b'0',
  `F_SL1Percentage` decimal(10,2) DEFAULT '0.00',
  `F_SL2Percentage` decimal(10,2) DEFAULT '0.00',
  `F_SLTimerInMinutes` int(11) DEFAULT '0',
  `F_TSLActivationPercentage` decimal(10,2) DEFAULT '0.00',
  `F_TSLTrailPercentage` decimal(10,2) DEFAULT '0.00',
  `S_TradingEnabled` bit(1) DEFAULT b'0',
  `S_SL1Percentage` decimal(10,2) DEFAULT '0.00',
  `S_SL2Percentage` decimal(10,2) DEFAULT '0.00',
  `S_SLTimerInMinutes` int(11) DEFAULT '0',
  `S_TSLActivationPercentage` decimal(10,2) DEFAULT '0.00',
  `S_TSLTrailPercentage` decimal(10,2) DEFAULT '0.00',
  PRIMARY KEY (`StrategyParametersId`),
  UNIQUE KEY `StrategyParametersId_UNIQUE` (`StrategyParametersId`)
) ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=utf8;

CREATE TABLE `trade` (
  `TradeId` int(11) NOT NULL AUTO_INCREMENT,
  `Symbol` varchar(45) DEFAULT NULL,
  `StrategyName` varchar(45) DEFAULT NULL,
  `IsOpen` bit(1) DEFAULT b'0',
  `TradeType` varchar(45) DEFAULT NULL,
  `Amount` decimal(20,8) DEFAULT '0.00000000',
  `QuoteAmount` decimal(20,8) DEFAULT '0.00000000',
  `EntryPrice` decimal(20,8) DEFAULT '0.00000000',
  `ExitPrice` decimal(20,8) DEFAULT '0.00000000',
  `StopLoss` decimal(20,8) DEFAULT '0.00000000',
  `EntryDate` datetime DEFAULT NULL,
  `ExitDate` datetime DEFAULT NULL,
  `EntryCandleDate` datetime DEFAULT NULL,
  `TimerInSeconds` int(11) DEFAULT '0',
  `EntryTriggerPrice` decimal(20,8) DEFAULT '0.00000000',
  `ExitTriggerPrice` decimal(20,8) DEFAULT '0.00000000',
  `ModifiedDate` datetime DEFAULT NULL,
  `CurrentPrice` decimal(20,8) DEFAULT '0.00000000',
  `PLAmount` decimal(20,8) DEFAULT '0.00000000',
  `PLPercentage` decimal(10,2) DEFAULT '0.00',
  `EntryCommission` decimal(20,8) DEFAULT '0.00000000',
  `ExitCommission` decimal(20,8) DEFAULT '0.00000000',
  PRIMARY KEY (`TradeId`),
  UNIQUE KEY `idnew_table_UNIQUE` (`TradeId`)
) ENGINE=InnoDB AUTO_INCREMENT=62 DEFAULT CHARSET=utf8;

CREATE TABLE `tradelog` (
  `TradeLogId` int(11) NOT NULL AUTO_INCREMENT,
  `TradeId` int(11) DEFAULT NULL,
  `Symbol` varchar(45) DEFAULT NULL,
  `CandleDate` datetime DEFAULT NULL,
  `CreatedDate` datetime DEFAULT NULL,
  `StrategyName` varchar(45) DEFAULT NULL,
  `TradeType` varchar(255) DEFAULT NULL,
  `Action` varchar(255) DEFAULT NULL,
  `Comment` varchar(255) DEFAULT NULL,
  `Amount` decimal(20,8) DEFAULT '0.00000000',
  `QuoteAmount` decimal(20,8) DEFAULT '0.00000000',
  `EntryPrice` decimal(20,8) DEFAULT '0.00000000',
  `CurrentPrice` decimal(20,8) DEFAULT '0.00000000',
  `StopLoss` decimal(20,8) DEFAULT '0.00000000',
  `PLAmount` decimal(20,8) DEFAULT '0.00000000',
  `PLPercentage` decimal(10,2) DEFAULT '0.00',
  `Commission` decimal(20,8) DEFAULT '0.00000000',
  `Balance` decimal(20,8) DEFAULT '0.00000000',
  PRIMARY KEY (`TradeLogId`),
  UNIQUE KEY `TradeLogId_UNIQUE` (`TradeLogId`)
) ENGINE=InnoDB AUTO_INCREMENT=341 DEFAULT CHARSET=utf8;
